class CfgFaces
{
	class Default
	{
		class Default
		{
			name="";
			head="";
			material="";
			texture="#(rgb,8,8,3)color(0.5,0.5,1,1)";
			textureHL="#(rgb,8,8,3)color(0.5,0.5,1,1)";
			materialHL="";
			identityTypes[]=
			{
				"Default"
			};
		};
		class Custom
		{
			name="";
			head="";
			material="";
			texture="#(rgb,8,8,3)color(1,1,1,1)";
			textureHL="#(rgb,8,8,3)color(0.5,0.5,1,1)";
			materialHL="";
			front="#(rgb,8,8,3)color(1,1,1,1)";
			side="#(rgb,8,8,3)color(1,1,1,1)";
			back="#(rgb,8,8,3)color(1,1,1,1)";
			identityTypes[]={};
		};
	};
	class Man_A3: Default
	{
		class Default
		{
			displayname="$STR_CFG_FACES_Default";
			texture="\A3\Characters_F\Heads\Data\m_White_01_co.paa";
			head="DefaultHead_A3";
			identityTypes[]={};
			material="A3\Characters_F\Heads\Data\m_White_01.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			disabled=0;
		};
		class Custom: Custom
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_CFG_FACES_CUSTOM";
			texture="#(argb,8,8,3)color(0.596,0.412,0.365,1)";
			head="DefaultHead_A3";
			identityTypes[]={};
			material="A3\Characters_F\Heads\Data\m_White_01.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_01_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_01_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
		};
		class PersianHead_A3_01: Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_TakistaniMen_LastNames11";
			texture="\A3\Characters_F\Heads\Data\m_persian_01_co.paa";
			textureHL="\A3\Characters_F\Heads\Data\hl_black_bald_co.paa";
			head="PersianHead_A3";
			identityTypes[]=
			{
				"Head_TK"
			};
			material="\A3\Characters_F\Heads\Data\m_persian_01.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_persian_01_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_persian_01_injury.rvmat";
		};
		class PersianHead_A3_02: PersianHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_TakistaniMen_LastNames27";
			texture="\A3\Characters_F\Heads\Data\m_persian_02_co.paa";
			material="\A3\Characters_F\Heads\Data\m_persian_02.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_persian_02_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_persian_02_injury.rvmat";
		};
		class PersianHead_A3_03: PersianHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_TakistaniMen_LastNames46";
			texture="\A3\Characters_F\Heads\Data\m_persian_03_co.paa";
			material="\A3\Characters_F\Heads\Data\m_persian_03.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_persian_03_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_persian_03_injury.rvmat";
		};
		class PersianHead_A3_04_a: PersianHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_cfgFaces_Man_A3_PersianHead_A3_04_a0";
			texture="\A3\Characters_F_Mark\Heads\Data\m_persian_04_a_co.paa";
			textureHL="\A3\Characters_F\Heads\Data\hl_white_hairy_3_co.paa";
			head="PersianHead_A3";
			identityTypes[]=
			{
				"Head_TK_camo_arid"
			};
			material="\A3\Characters_F_Mark\Heads\Data\m_persian_04_a.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_persian_04_a_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_persian_04_a_injury.rvmat";
			DLC="Mark";
		};
		class PersianHead_A3_04_l: PersianHead_A3_04_a
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_cfgFaces_Man_A3_PersianHead_A3_04_l0";
			identityTypes[]=
			{
				"Head_TK_camo_lush"
			};
			texture="\A3\Characters_F_Mark\Heads\Data\m_persian_04_l_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_persian_04_l.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_persian_04_l_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_persian_04_l_injury.rvmat";
			DLC="Mark";
		};
		class PersianHead_A3_04_sa: PersianHead_A3_04_a
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_cfgFaces_Man_A3_PersianHead_A3_04_sa0";
			identityTypes[]=
			{
				"Head_TK_camo_semiarid"
			};
			texture="\A3\Characters_F_Mark\Heads\Data\m_persian_04_sa_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_persian_04_sa.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_persian_04_sa_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_persian_04_sa_injury.rvmat";
			DLC="Mark";
		};
		class WhiteHead_01: Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames90";
			texture="\A3\Characters_F\Heads\Data\m_White_01_co.paa";
			head="NATOHead_A3";
			identityTypes[]=
			{
				"Head_NATO",
				"Head_Euro"
			};
			material="\A3\Characters_F\Heads\Data\m_White_01.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_01_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_01_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_1_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
		};
		class WhiteHead_02: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames91";
			texture="\A3\Characters_F\Heads\Data\m_White_02_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_02.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_2_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_02_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_02_injury.rvmat";
		};
		class WhiteHead_03: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames92";
			texture="\A3\Characters_F\Heads\Data\m_White_03_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_03.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_03_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_03_injury.rvmat";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_02_bald_muscular.rvmat";
		};
		class WhiteHead_04: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames93";
			texture="\A3\Characters_F\Heads\Data\m_White_04_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_04.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_2_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_04_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_04_injury.rvmat";
		};
		class WhiteHead_05: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames94";
			texture="\A3\Characters_F\Heads\Data\m_White_05_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_05.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_1_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_05_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_05_injury.rvmat";
		};
		class WhiteHead_06: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames95";
			texture="\A3\Characters_F\Heads\Data\m_White_06_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_06.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_3_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_06_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_06_injury.rvmat";
		};
		class WhiteHead_07: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames96";
			texture="\A3\Characters_F\Heads\Data\m_White_07_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_07.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_07_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_07_injury.rvmat";
		};
		class WhiteHead_08: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames97";
			texture="\A3\Characters_F\Heads\Data\m_White_08_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_08.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_08_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_08_injury.rvmat";
		};
		class WhiteHead_09: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames98";
			texture="\A3\Characters_F\Heads\Data\m_White_09_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_09.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_3_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_09_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_09_injury.rvmat";
		};
		class WhiteHead_10: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames103";
			texture="\A3\Characters_F\Heads\Data\m_White_10_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_10.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_2_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_10_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_10_injury.rvmat";
		};
		class WhiteHead_11: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames100";
			texture="\A3\Characters_F\Heads\Data\m_White_11_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_11.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_11_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_11_injury.rvmat";
		};
		class WhiteHead_12: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames106";
			texture="\A3\Characters_F\Heads\Data\m_White_12_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_12.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_12_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_12_injury.rvmat";
		};
		class WhiteHead_13: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames107";
			texture="\A3\Characters_F\Heads\Data\m_White_13_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_13.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_2_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_13_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_13_injury.rvmat";
		};
		class WhiteHead_14: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames108";
			texture="\A3\Characters_F\Heads\Data\m_White_14_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_14.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_2_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_14_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_14_injury.rvmat";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_02_bald_muscular.rvmat";
		};
		class WhiteHead_15: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames109";
			texture="\A3\Characters_F\Heads\Data\m_White_15_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_15.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_2_co.paa";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_15_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_15_injury.rvmat";
		};
		class WhiteHead_16: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames83";
			texture="\A3\Characters_F_EPB\Heads\Data\m_white_16_co.paa";
			material="\A3\Characters_F_EPB\Heads\Data\m_white_16.rvmat";
			materialWounded1="\A3\Characters_F_EPB\Heads\Data\m_white_16_injury.rvmat";
			materialWounded2="\A3\Characters_F_EPB\Heads\Data\m_white_16_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
		};
		class WhiteHead_17: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames89";
			texture="\A3\Characters_F_EPB\Heads\Data\m_white_17_co.paa";
			material="\A3\Characters_F_EPB\Heads\Data\m_white_17.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_3_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_3_co.paa";
			materialHL="A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
			materialWounded1="\A3\Characters_F_EPB\Heads\Data\m_white_17_injury.rvmat";
			materialWounded2="\A3\Characters_F_EPB\Heads\Data\m_white_17_injury.rvmat";
		};
		class WhiteHead_18: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames87";
			texture="\A3\Characters_F_EPB\Heads\Data\m_white_18_co.paa";
			material="\A3\Characters_F_EPB\Heads\Data\m_white_18.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_white_hairy_2_co.paa";
			materialWounded1="\A3\Characters_F_EPB\Heads\Data\m_white_18_injury.rvmat";
			materialWounded2="\A3\Characters_F_EPB\Heads\Data\m_white_18_injury.rvmat";
		};
		class WhiteHead_19: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames86";
			texture="\A3\Characters_F_EPB\Heads\Data\m_white_19_co.paa";
			material="\A3\Characters_F_EPB\Heads\Data\m_white_19.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_2_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_2_co.paa";
			materialWounded1="\A3\Characters_F_EPB\Heads\Data\m_white_19_injury.rvmat";
			materialWounded2="\A3\Characters_F_EPB\Heads\Data\m_white_19_injury.rvmat";
		};
		class WhiteHead_20: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames85";
			identityTypes[]=
			{
				"Head_NATO",
				"Head_Euro",
				"Tanker"
			};
			texture="\A3\Characters_F_EPB\Heads\Data\m_white_20_co.paa";
			material="\A3\Characters_F_EPB\Heads\Data\m_white_20.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_3_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_3_co.paa";
			materialWounded1="\A3\Characters_F_EPB\Heads\Data\m_white_20_injury.rvmat";
			materialWounded2="\A3\Characters_F_EPB\Heads\Data\m_white_20_injury.rvmat";
		};
		class WhiteHead_21: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames84";
			texture="\A3\Characters_F_EPB\Heads\Data\m_white_21_co.paa";
			material="\A3\Characters_F_EPB\Heads\Data\m_white_21.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialWounded1="\A3\Characters_F_EPB\Heads\Data\m_white_21_injury.rvmat";
			materialWounded2="\A3\Characters_F_EPB\Heads\Data\m_white_21_injury.rvmat";
		};
		class WhiteHead_22_a: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_cfgFaces_Man_A3_WhiteHead_22_a0";
			identityTypes[]=
			{
				"Head_NATO_camo_arid"
			};
			texture="\A3\Characters_F_Mark\Heads\Data\m_White_22_a_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_White_22_a.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_White_22_a_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_White_22_a_injury.rvmat";
			DLC="Mark";
		};
		class WhiteHead_22_l: WhiteHead_22_a
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_cfgFaces_Man_A3_WhiteHead_22_l0";
			identityTypes[]=
			{
				"Head_NATO_camo_lush"
			};
			texture="\A3\Characters_F_Mark\Heads\Data\m_White_22_l_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_White_22_L.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_White_22_l_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_White_22_l_injury.rvmat";
			DLC="Mark";
		};
		class WhiteHead_22_sa: WhiteHead_22_a
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_cfgFaces_Man_A3_WhiteHead_22_sa0";
			identityTypes[]=
			{
				"Head_NATO_camo_semiarid"
			};
			texture="\A3\Characters_F_Mark\Heads\Data\m_White_22_sa_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_White_22_sa.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_White_22_sa_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_White_22_sa_injury.rvmat";
			DLC="Mark";
		};
		class AfricanHead_01: Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_NATOMen_LastNames112";
			texture="\A3\Characters_F\Heads\Data\m_african_01_co.paa";
			head="BlackHead_A3";
			identityTypes[]=
			{
				"Head_NATO",
				"Head_African"
			};
			material="\A3\Characters_F\Heads\Data\m_african_01.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_african_01_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_african_01_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_black_bald_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_black_bald_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat";
		};
		class AfricanHead_02: AfricanHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_AFROMEN_FIRSTNAMES9";
			texture="\A3\Characters_F\Heads\Data\m_african_02_co.paa";
			material="\A3\Characters_F\Heads\Data\m_african_02.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_african_02_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_african_02_injury.rvmat";
		};
		class AfricanHead_03: AfricanHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CivMen_FirstNames26";
			texture="\A3\Characters_F\Heads\Data\m_african_03_co.paa";
			material="\A3\Characters_F\Heads\Data\m_african_03.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_african_03_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_african_03_injury.rvmat";
		};
		class GreekHead_A3_01: Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_GreekMen_LastNames0";
			texture="\A3\Characters_F\Heads\Data\m_Greek_01_co.paa";
			head="GreekHead_A3";
			identityTypes[]=
			{
				"Head_Greek"
			};
			material="\A3\Characters_F\Heads\Data\m_Greek_01.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_Greek_01_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_Greek_01_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_3_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_3_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
		};
		class GreekHead_A3_02: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_GreekMen_LastNames3";
			texture="\A3\Characters_F\Heads\Data\m_Greek_02_co.paa";
			material="\A3\Characters_F\Heads\Data\m_Greek_02.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_Greek_02_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_Greek_02_injury.rvmat";
		};
		class GreekHead_A3_03: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_GreekMen_LastNames5";
			texture="\A3\Characters_F\Heads\Data\m_Greek_03_co.paa";
			material="\A3\Characters_F\Heads\Data\m_Greek_03.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_Greek_03_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_Greek_03_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_old_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_old.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_old_1_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_old.rvmat";
			identityTypes[]=
			{
				"Head_Greek",
				"Head_Rangemaster"
			};
		};
		class GreekHead_A3_04: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_GreekMen_LastNames7";
			texture="\A3\Characters_F\Heads\Data\m_Greek_04_co.paa";
			material="\A3\Characters_F\Heads\Data\m_Greek_04.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_Greek_04_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_Greek_04_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_old_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_old.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_old_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_old.rvmat";
		};
		class GreekHead_A3_05: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_GreekMen_LastNames11";
			texture="\A3\Characters_F\Heads\Data\m_White_01_co.paa";
			identityTypes[]=
			{
				"Head_NATO",
				"Head_Greek"
			};
			material="\A3\Characters_F\Heads\Data\m_White_01.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_01_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_01_injury.rvmat";
		};
		class GreekHead_A3_06: GreekHead_A3_05
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_GreekMen_LastNames15";
			texture="\A3\Characters_F\Heads\Data\m_White_02_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_02.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_02_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_02_injury.rvmat";
		};
		class GreekHead_A3_07: GreekHead_A3_05
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_GreekMen_LastNames17";
			texture="\A3\Characters_F\Heads\Data\m_White_03_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_03.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_03_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_03_injury.rvmat";
		};
		class GreekHead_A3_08: GreekHead_A3_05
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_GreekMen_LastNames21";
			texture="\A3\Characters_F\Heads\Data\m_White_04_co.paa";
			material="\A3\Characters_F\Heads\Data\m_White_04.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_04_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_04_injury.rvmat";
		};
		class GreekHead_A3_09: GreekHead_A3_05
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_GreekMen_LastNames53";
			texture="\A3\Characters_F\Heads\Data\m_White_05_co.paa";
			identityTypes[]=
			{
				"Head_NATO",
				"Head_Greek"
			};
			material="\A3\Characters_F\Heads\Data\m_White_05.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_White_05_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_White_05_injury.rvmat";
		};
		class GreekHead_A3_10_a: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_cfgFaces_Man_A3_GreekHead_A3_10_a0";
			identityTypes[]=
			{
				"Head_Greek_camo_arid"
			};
			texture="\A3\Characters_F_Mark\Heads\Data\m_Greek_10_a_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_Greek_10_a.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_Greek_10_a_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_Greek_10_a_injury.rvmat";
			DLC="Mark";
		};
		class GreekHead_A3_10_l: GreekHead_A3_10_a
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_cfgFaces_Man_A3_GreekHead_A3_10_l0";
			identityTypes[]=
			{
				"Head_Greek_camo_lush"
			};
			texture="\A3\Characters_F_Mark\Heads\Data\m_Greek_10_l_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_Greek_10_l.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_Greek_10_l_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_Greek_10_l_injury.rvmat";
			DLC="Mark";
		};
		class GreekHead_A3_10_sa: GreekHead_A3_10_a
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_cfgFaces_Man_A3_GreekHead_A3_10_sa0";
			identityTypes[]=
			{
				"Head_Greek_camo_semiarid"
			};
			texture="\A3\Characters_F_Mark\Heads\Data\m_Greek_10_sa_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_Greek_10_sa.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_Greek_10_sa_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_Greek_10_sa_injury.rvmat";
			DLC="Mark";
		};
		class AsianHead_A3_01: Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_AsianMen_LastNames24";
			texture="\A3\Characters_F\Heads\Data\m_Asian_01_co.paa";
			head="AsianHead_A3";
			identityTypes[]=
			{
				"Head_Asian"
			};
			material="\A3\Characters_F\Heads\Data\m_Asian_01.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_Asian_01_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_Asian_01_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat";
		};
		class AsianHead_A3_02: AsianHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_AsianMen_LastNames7";
			texture="\A3\Characters_F\Heads\Data\m_Asian_02_co.paa";
			material="\A3\Characters_F\Heads\Data\m_Asian_02.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_Asian_02_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_Asian_02_injury.rvmat";
		};
		class AsianHead_A3_03: AsianHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_AsianMen_LastNames21";
			texture="\A3\Characters_F\Heads\Data\m_Asian_03_co.paa";
			material="\A3\Characters_F\Heads\Data\m_Asian_03.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_Asian_03_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_Asian_03_injury.rvmat";
		};
		class Nikos: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CfgFaces_Man_A3_Nikos0";
			head="Nikos";
			texture="\A3\Characters_F\Heads\Data\m_nikos_co.paa";
			identityTypes[]=
			{
				"Nikos"
			};
			material="\A3\Characters_F\Heads\Data\m_nikos.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_nikos_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_nikos_injury.rvmat";
			disabled=1;
		};
		class Miller: Default
		{
			displayname="$STR_A3_CfgFaces_Man_A3_Miller0";
			head="Miller";
			texture="\A3\Characters_F\Heads\Data\m_Miller_co.paa";
			identityTypes[]=
			{
				"Miller"
			};
			material="\A3\Characters_F\Heads\Data\m_Miller.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_Miller_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_Miller_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			disabled=1;
		};
		class Kerry: Default
		{
			head="KerryHead_A3";
			texture="\A3\Characters_F_EPA\Heads\Data\m_kerry_A_co.paa";
			identityTypes[]=
			{
				"Kerry"
			};
			material="A3\Characters_F_EPA\Heads\Data\m_kerry_A.rvmat";
			materialWounded1="A3\Characters_F_EPA\Heads\Data\m_kerry_A_injury.rvmat";
			materialWounded2="A3\Characters_F_EPA\Heads\Data\m_kerry_A_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			disabled=1;
		};
		class Kerry_A_F: Kerry
		{
			identityTypes[]=
			{
				"Kerry_A"
			};
		};
		class kerry_B1_F: Kerry
		{
			texture="\A3\Characters_F_EPA\Heads\Data\m_kerry_B1_co.paa";
			identityTypes[]=
			{
				"kerry_B1"
			};
			material="A3\Characters_F_EPA\Heads\Data\m_kerry_B1.rvmat";
			materialWounded1="A3\Characters_F_EPA\Heads\Data\m_kerry_b1_injury.rvmat";
			materialWounded2="A3\Characters_F_EPA\Heads\Data\m_kerry_b1_injury.rvmat";
		};
		class kerry_B2_F: Kerry
		{
			texture="\A3\Characters_F_EPA\Heads\Data\m_kerry_B2_co.paa";
			identityTypes[]=
			{
				"kerry_B2"
			};
			material="A3\Characters_F_EPA\Heads\Data\m_kerry_B2.rvmat";
			materialWounded1="A3\Characters_F_EPA\Heads\Data\m_kerry_b2_injury.rvmat";
			materialWounded2="A3\Characters_F_EPA\Heads\Data\m_kerry_b2_injury.rvmat";
			textureHL="\A3\Characters_F_EPB\Heads\Data\hl_hairy_dirty_co.paa";
			materialHL="\A3\Characters_F_EPB\Heads\Data\hl_hairy_dirty.rvmat";
			textureHL2="\A3\Characters_F_EPB\Heads\Data\hl_hairy_dirty_co.paa";
			materialHL2="A3\Characters_F_EPB\Heads\Data\hl_hairy_dirty.rvmat";
		};
		class Kerry_C_F: Kerry
		{
			texture="\A3\Characters_F_EPA\Heads\Data\m_kerry_C_co.paa";
			identityTypes[]=
			{
				"Kerry_C"
			};
			material="A3\Characters_F_EPA\Heads\Data\m_kerry_C.rvmat";
			materialWounded1="A3\Characters_F_EPA\Heads\Data\m_kerry_C_injury.rvmat";
			materialWounded2="A3\Characters_F_EPA\Heads\Data\m_kerry_C_injury.rvmat";
		};
		class IG_Leader: Default
		{
			displayname="$STR_A3_I_G_resistanceLeader_F0";
			head="IG_Leader";
			texture="\A3\Characters_F_EPB\Heads\Data\m_IG_leader_co.paa";
			identityTypes[]=
			{
				"IG_Leader"
			};
			material="\A3\Characters_F_EPB\Heads\Data\m_IG_leader.rvmat";
			materialWounded1="A3\characters_F_EPB\Heads\Data\m_IG_leader_injury.rvmat";
			materialWounded2="A3\characters_F_EPB\Heads\Data\m_IG_leader_injury.rvmat";
			textureHL="\A3\Characters_F_EPB\Heads\Data\hl_Stavrou_dirty_co.paa";
			materialHL="\A3\Characters_F_EPB\Heads\Data\hl_stavrou_dirty.rvmat";
			textureHL2="\A3\Characters_F_EPB\Heads\Data\hl_Stavrou_dirty_co.paa";
			materialHL2="A3\Characters_F_EPB\Heads\Data\hl_stavrou_dirty.rvmat";
			disabled=1;
		};
		class O_Colonel: Default
		{
			displayname="$STR_A3_O_STORY_COLONEL_F0";
			head="PersianHead_A3";
			texture="\A3\Characters_F_EPB\Heads\Data\m_white_17_co.paa";
			identityTypes[]=
			{
				"O_Colonel"
			};
			material="\A3\Characters_F_EPB\Heads\Data\m_white_17.rvmat";
			materialWounded1="\A3\Characters_F_EPB\Heads\Data\m_white_17_injury.rvmat";
			materialWounded2="\A3\Characters_F_EPB\Heads\Data\m_white_17_injury.rvmat";
			disabled=1;
		};
		class Jay: Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CfgFaces_Man_A3_Jay0";
			head="Jay";
			texture="\A3\Characters_F\Heads\Data\m_Jay_co.paa";
			identityTypes[]=
			{
				"Jay"
			};
			material="\A3\Characters_F\Heads\Data\m_Jay.rvmat";
			materialWounded1="\A3\Characters_F\Heads\Data\m_Jay_injury.rvmat";
			materialWounded2="\A3\Characters_F\Heads\Data\m_Jay_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			disabled=1;
		};
		class Ivan: Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CfgFaces_Man_A3_Ivan0";
			head="Ivan";
			texture="\A3\Characters_F\Heads\Data\m_Ivan_co.paa";
			identityTypes[]=
			{
				"Ivan"
			};
			material="\A3\Characters_F\Heads\Data\m_Ivan.rvmat";
			materialWounded1="\A3\Characters_F\Heads\Data\m_Ivan_injury.rvmat";
			materialWounded2="\A3\Characters_F\Heads\Data\m_Ivan_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			disabled=1;
		};
		class Pettka: Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CfgFaces_Man_A3_Pettka0";
			head="Pettka";
			texture="\A3\Characters_F\Heads\Data\m_Pettka_co.paa";
			identityTypes[]=
			{
				"Pettka"
			};
			material="\A3\Characters_F\Heads\Data\m_Pettka.rvmat";
			materialWounded1="\A3\Characters_F\Heads\Data\m_Pettka_injury.rvmat";
			materialWounded2="\A3\Characters_F\Heads\Data\m_Pettka_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			disabled=1;
		};
		class Dwarden: Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CfgFaces_Man_A3_Dwarden0";
			head="Dwarden";
			texture="\A3\Characters_F\Heads\Data\m_Dwarden_co.paa";
			identityTypes[]=
			{
				"Dwarden"
			};
			material="\A3\Characters_F\Heads\Data\m_Dwarden.rvmat";
			materialWounded1="\A3\Characters_F\Heads\Data\m_Dwarden_injury.rvmat";
			materialWounded2="\A3\Characters_F\Heads\Data\m_Dwarden_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			disabled=1;
		};
		class Hladas: Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CfgFaces_Man_A3_Hladas0";
			head="Hladas";
			texture="\A3\Characters_F\Heads\Data\m_Hladas_co.paa";
			identityTypes[]=
			{
				"Hladas"
			};
			material="\A3\Characters_F\Heads\Data\m_Hladas.rvmat";
			materialWounded1="\A3\Characters_F\Heads\Data\m_Hladas_injury.rvmat";
			materialWounded2="\A3\Characters_F\Heads\Data\m_Hladas_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			disabled=1;
		};
		class CamoHead_White_01_F: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_01";
			texture="\A3\Characters_F\Heads\Data\m_White_01_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_01.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_01_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_01_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_02_F: WhiteHead_02
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_02";
			texture="\A3\Characters_F\Heads\Data\m_White_02_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_02.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_02_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_02_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_03_F: WhiteHead_03
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_03";
			texture="\A3\Characters_F\Heads\Data\m_White_03_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_03.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_03_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_03_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_04_F: WhiteHead_04
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_04";
			texture="\A3\Characters_F\Heads\Data\m_White_04_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_04.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_04_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_04_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_05_F: WhiteHead_05
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_05";
			texture="\A3\Characters_F\Heads\Data\m_White_05_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_05.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_05_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_05_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_06_F: WhiteHead_06
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_06";
			texture="\A3\Characters_F\Heads\Data\m_White_06_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_06.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_06_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_06_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_07_F: WhiteHead_07
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_07";
			texture="\A3\Characters_F\Heads\Data\m_White_07_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_07.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_07_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_07_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_08_F: WhiteHead_08
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_08";
			texture="\A3\Characters_F\Heads\Data\m_White_08_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_08.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_08_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_08_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_09_F: WhiteHead_09
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_09";
			texture="\A3\Characters_F\Heads\Data\m_White_09_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_09.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_09_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_09_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_10_F: WhiteHead_10
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_10";
			texture="\A3\Characters_F\Heads\Data\m_White_10_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_10.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_10_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_10_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_11_F: WhiteHead_11
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_11";
			texture="\A3\Characters_F\Heads\Data\m_White_11_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_11.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_11_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_11_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_12_F: WhiteHead_12
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_12";
			texture="\A3\Characters_F\Heads\Data\m_White_12_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_12.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_12_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_12_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_13_F: WhiteHead_13
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_13";
			texture="\A3\Characters_F\Heads\Data\m_White_13_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_13.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_13_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_13_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_14_F: WhiteHead_14
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_14";
			texture="\A3\Characters_F\Heads\Data\m_White_14_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_14.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_14_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_14_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_15_F: WhiteHead_15
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_15";
			texture="\A3\Characters_F\Heads\Data\m_White_15_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_15.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_15_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_15_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_16_F: WhiteHead_16
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_16";
			texture="\A3\Characters_F_EPB\Heads\Data\m_White_16_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_16.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_16_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_16_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_17_F: WhiteHead_17
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_17";
			texture="\A3\Characters_F_EPB\Heads\Data\m_White_17_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_17.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_17_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_17_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_18_F: WhiteHead_18
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_18";
			texture="\A3\Characters_F_EPB\Heads\Data\m_White_18_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_18.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_18_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_18_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_19_F: WhiteHead_19
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_19";
			texture="\A3\Characters_F_EPB\Heads\Data\m_White_19_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_19.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_19_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_19_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_20_F: WhiteHead_20
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_20";
			texture="\A3\Characters_F_EPB\Heads\Data\m_White_20_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_20.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_20_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_20_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_White_21_F: WhiteHead_21
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_White_21";
			texture="\A3\Characters_F_EPB\Heads\Data\m_White_21_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_21.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_21_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_21_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_African_01_F: AfricanHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_African_01";
			texture="\A3\Characters_F\Heads\Data\m_African_01_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_African_01.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_African_01_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_African_01_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_African_02_F: AfricanHead_02
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_African_02";
			texture="\A3\Characters_F\Heads\Data\m_African_02_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_African_02.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_African_02_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_African_02_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_African_03_F: AfricanHead_03
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_African_03";
			texture="\A3\Characters_F\Heads\Data\m_African_03_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_African_03.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_African_03_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_African_03_injury.rvmat";
			identityTypes[]=
			{
				"Head_NATO_camo_lush",
				"Head_NATO_camo_arid",
				"Head_NATO_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Greek_01_F: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Greek_01";
			texture="\A3\Characters_F\Heads\Data\m_Greek_01_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_Greek_01.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_Greek_01_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_Greek_01_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Greek_02_F: GreekHead_A3_02
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Greek_02";
			texture="\A3\Characters_F\Heads\Data\m_Greek_02_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_Greek_02.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_Greek_02_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_Greek_02_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Greek_03_F: GreekHead_A3_03
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Greek_03";
			texture="\A3\Characters_F\Heads\Data\m_Greek_03_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_Greek_03.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_Greek_03_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_Greek_03_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Greek_04_F: GreekHead_A3_04
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Greek_04";
			texture="\A3\Characters_F\Heads\Data\m_Greek_04_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_Greek_04.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_Greek_04_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_Greek_04_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Greek_05_F: GreekHead_A3_05
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Greek_05";
			texture="\A3\Characters_F\Heads\Data\m_White_01_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_01.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_01_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_01_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Greek_06_F: GreekHead_A3_06
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Greek_06";
			texture="\A3\Characters_F\Heads\Data\m_White_02_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_02.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_02_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_02_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Greek_07_F: GreekHead_A3_07
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Greek_07";
			texture="\A3\Characters_F\Heads\Data\m_White_03_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_03.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_03_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_03_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Greek_08_F: GreekHead_A3_08
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Greek_08";
			texture="\A3\Characters_F\Heads\Data\m_White_04_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_04.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_04_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_04_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Greek_09_F: GreekHead_A3_09
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Greek_09";
			texture="\A3\Characters_F\Heads\Data\m_White_05_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_White_05.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_White_05_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_White_05_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Asian_01_F: AsianHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Asian_01";
			texture="\A3\Characters_F\Heads\Data\m_Asian_01_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_Asian_01.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_Asian_01_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_Asian_01_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Asian_02_F: AsianHead_A3_02
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Asian_02";
			texture="\A3\Characters_F\Heads\Data\m_Asian_02_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_Asian_02.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_Asian_02_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_Asian_02_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Asian_03_F: AsianHead_A3_03
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Asian_03";
			texture="\A3\Characters_F\Heads\Data\m_Asian_03_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_Asian_03.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_Asian_03_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_Asian_03_injury.rvmat";
			identityTypes[]=
			{
				"Head_Greek_camo_lush",
				"Head_Greek_camo_arid",
				"Head_Greek_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Persian_01_F: PersianHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Persian_01";
			texture="\A3\Characters_F\Heads\Data\m_Persian_01_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_Persian_01.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_Persian_01_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_Persian_01_injury.rvmat";
			identityTypes[]=
			{
				"Head_TK_camo_lush",
				"Head_TK_camo_arid",
				"Head_TK_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Persian_02_F: PersianHead_A3_02
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Persian_02";
			texture="\A3\Characters_F\Heads\Data\m_Persian_02_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_Persian_02.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_Persian_02_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_Persian_02_injury.rvmat";
			identityTypes[]=
			{
				"Head_TK_camo_lush",
				"Head_TK_camo_arid",
				"Head_TK_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class CamoHead_Persian_03_F: PersianHead_A3_03
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="Camo_Persian_03";
			texture="\A3\Characters_F\Heads\Data\m_Persian_03_co.paa";
			material="\A3\Characters_F_Mark\Heads\Data\m_camo_Persian_03.rvmat";
			materialWounded1="A3\Characters_F_Mark\Heads\Data\m_camo_Persian_03_injury.rvmat";
			materialWounded2="A3\Characters_F_Mark\Heads\Data\m_camo_Persian_03_injury.rvmat";
			identityTypes[]=
			{
				"Head_TK_camo_lush",
				"Head_TK_camo_arid",
				"Head_TK_camo_semiarid"
			};
			disabled=1;
			DLC="Mark";
		};
		class TanoanHead_A3_01: Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_TanoanHead_A3_010";
			texture="\A3\Characters_F_Exp\Heads\Data\m_tanoan_01_co.paa";
			head="TanoanHead_A3";
			identityTypes[]=
			{
				"Head_Tanoan"
			};
			material="A3\Characters_F_Exp\Heads\Data\m_tanoan_01.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_tanoan_01_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_tanoan_01_injury.rvmat";
			textureHL="A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_co.paa";
			materialHL="A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat";
			textureHL2="A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_co.paa";
			materialHL2="A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat";
			DLC="Expansion";
		};
		class TanoanHead_A3_02: TanoanHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_TanoanHead_A3_020";
			texture="\A3\Characters_F_Exp\Heads\Data\m_tanoan_02_co.paa";
			material="A3\Characters_F_Exp\Heads\Data\m_tanoan_02.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_tanoan_02_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_tanoan_02_injury.rvmat";
			DLC="Expansion";
		};
		class TanoanHead_A3_03: TanoanHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_TanoanHead_A3_030";
			texture="\A3\Characters_F_Exp\Heads\Data\m_tanoan_03_co.paa";
			material="A3\Characters_F_Exp\Heads\Data\m_tanoan_03.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_tanoan_03_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_tanoan_03_injury.rvmat";
			DLC="Expansion";
		};
		class TanoanHead_A3_04: TanoanHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_TanoanHead_A3_040";
			texture="\A3\Characters_F_Exp\Heads\Data\m_tanoan_04_co.paa";
			material="A3\Characters_F_Exp\Heads\Data\m_tanoan_04.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_tanoan_04_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_tanoan_04_injury.rvmat";
			DLC="Expansion";
		};
		class TanoanHead_A3_05: TanoanHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_TanoanHead_A3_050";
			texture="\A3\Characters_F_Exp\Heads\Data\m_tanoan_05_co.paa";
			material="A3\Characters_F_Exp\Heads\Data\m_tanoan_05.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_tanoan_05_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_tanoan_05_injury.rvmat";
			DLC="Expansion";
			textureHL="\A3\Characters_F\Heads\Data\hl_black_bald_co.paa";
		};
		class TanoanHead_A3_06: TanoanHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_TanoanHead_A3_060";
			texture="\A3\Characters_F_Exp\Heads\Data\m_tanoan_06_co.paa";
			material="A3\Characters_F_Exp\Heads\Data\m_tanoan_06.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_tanoan_06_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_tanoan_06_injury.rvmat";
			DLC="Expansion";
		};
		class TanoanHead_A3_07: TanoanHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_TanoanHead_A3_070";
			texture="\A3\Characters_F_Exp\Heads\Data\m_tanoan_07_co.paa";
			material="A3\Characters_F_Exp\Heads\Data\m_tanoan_07.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_tanoan_07_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_tanoan_07_injury.rvmat";
			DLC="Expansion";
		};
		class TanoanHead_A3_08: TanoanHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_TanoanHead_A3_080";
			texture="\A3\Characters_F_Exp\Heads\Data\m_tanoan_08_co.paa";
			material="A3\Characters_F_Exp\Heads\Data\m_tanoan_08.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_tanoan_08_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_tanoan_08_injury.rvmat";
			DLC="Expansion";
		};
		class TanoanBossHead: TanoanHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_I_C_Soldier_Camo_F0";
			identityTypes[]=
			{
				"Syndikat_Boss_F"
			};
			texture="\A3\Characters_F_Exp\Heads\Data\m_tanoan_boss_co.paa";
			material="A3\Characters_F_Exp\Heads\Data\m_tanoan_boss.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_tanoan_boss_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_tanoan_boss_injury.rvmat";
			disabled=1;
			DLC="Expansion";
		};
		class AsianHead_A3_04: AsianHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CfgFaces_Man_A3_AsianHead_A3_040";
			texture="\A3\Characters_F_Exp\Heads\Data\m_Asian_04_co.paa";
			material="\A3\Characters_F_Exp\Heads\Data\m_Asian_04.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_Asian_04_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_Asian_04_injury.rvmat";
			materialHL2="\A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat";
			DLC="Expansion";
		};
		class AsianHead_A3_05: AsianHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CfgFaces_Man_A3_AsianHead_A3_050";
			texture="\A3\Characters_F_Exp\Heads\Data\m_Asian_05_co.paa";
			material="\A3\Characters_F_Exp\Heads\Data\m_Asian_05.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_Asian_05_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_Asian_05_injury.rvmat";
			materialHL2="\A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat";
			DLC="Expansion";
		};
		class AsianHead_A3_06: AsianHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CfgFaces_Man_A3_AsianHead_A3_060";
			texture="\A3\Characters_F_Exp\Heads\Data\m_Asian_06_co.paa";
			material="\A3\Characters_F_Exp\Heads\Data\m_Asian_06.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_Asian_06_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_Asian_06_injury.rvmat";
			materialHL2="\A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat";
			DLC="Expansion";
		};
		class AsianHead_A3_07: AsianHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CfgFaces_Man_A3_AsianHead_A3_070";
			texture="\A3\Characters_F_Exp\Heads\Data\m_Asian_07_co.paa";
			material="\A3\Characters_F_Exp\Heads\Data\m_Asian_07.rvmat";
			materialWounded1="A3\Characters_F_Exp\Heads\Data\m_Asian_07_injury.rvmat";
			materialWounded2="A3\Characters_F_Exp\Heads\Data\m_Asian_07_injury.rvmat";
			materialHL2="\A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat";
			DLC="Expansion";
		};
		class GreekHead_A3_11: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_GreekHead_A3_110";
			identityTypes[]=
			{
				"Orange_Officer"
			};
			texture="a3\Characters_F_Orange\Heads\data\m_Greek_11_co.paa";
			material="a3\Characters_F_Orange\Heads\data\m_Greek_11.rvmat";
			materialWounded1="a3\Characters_F_Orange\Heads\data\m_Greek_11_injury.rvmat";
			materialWounded2="a3\Characters_F_Orange\Heads\data\m_Greek_11_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_4_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_4_co.paa";
			DLC="Orange";
		};
		class GreekHead_A3_12: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_GreekHead_A3_120";
			identityTypes[]=
			{
				"Orange_Civilian"
			};
			texture="a3\Characters_F_Orange\Heads\data\m_Greek_12_co.paa";
			material="a3\Characters_F_Orange\Heads\data\m_Greek_12.rvmat";
			materialWounded1="a3\Characters_F_Orange\Heads\data\m_Greek_12_injury.rvmat";
			materialWounded2="a3\Characters_F_Orange\Heads\data\m_Greek_12_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_4_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_4_co.paa";
			DLC="Orange";
		};
		class GreekHead_A3_13: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_GreekHead_A3_130";
			identityTypes[]=
			{
				"Orange_FIA"
			};
			texture="a3\Characters_F_Orange\Heads\data\m_Greek_13_co.paa";
			material="a3\Characters_F_Orange\Heads\data\m_Greek_13.rvmat";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_4_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_4_co.paa";
			materialWounded1="a3\Characters_F_Orange\Heads\data\m_Greek_13_injury.rvmat";
			materialWounded2="a3\Characters_F_Orange\Heads\data\m_Greek_13_injury.rvmat";
			DLC="Orange";
		};
		class GreekHead_A3_14: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_CfgFaces_Man_A3_GreekHead_A3_140";
			identityTypes[]=
			{
				"Orange_AAF"
			};
			texture="a3\Characters_F_Orange\Heads\data\m_Greek_14_co.paa";
			material="a3\Characters_F_Orange\Heads\data\m_Greek_14.rvmat";
			materialWounded1="a3\Characters_F_Orange\Heads\data\m_Greek_14_injury.rvmat";
			materialWounded2="a3\Characters_F_Orange\Heads\data\m_Greek_14_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_4_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_4_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_bald_muscular.rvmat";
			DLC="Orange";
		};
		class WhiteHead_23: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_Orange_Campaign_CfgIdentities_EOD_nameShort";
			identityTypes[]=
			{
				"Orange_EOD"
			};
			texture="a3\Characters_F_Orange\Heads\data\m_white_22_co.paa";
			material="a3\Characters_F_Orange\Heads\data\m_white_22.rvmat";
			materialWounded1="a3\Characters_F_Orange\Heads\data\m_white_22_injury.rvmat";
			materialWounded2="a3\Characters_F_Orange\Heads\data\m_white_22_injury.rvmat";
			DLC="Orange";
		};
		class Barklem: AfricanHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_TO_C03_CFGIDENTITIES_BARKLEM_NAMESHORT";
			texture="\A3\Characters_F_Tacops\Heads\Data\m_Barklem_co.paa";
			material="\A3\Characters_F_Tacops\Heads\Data\m_Barklem.rvmat";
		};
		class Mavros: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_TO_C01_CFGIDENTITIES_MAVROS_NAMESHORT";
			texture="\A3\Characters_F_Tacops\Heads\Data\m_Mavros_co.paa";
			material="\A3\Characters_F_Tacops\Heads\Data\m_Mavros.rvmat";
		};
		class Sturrock: WhiteHead_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_TO_C03_CFGIDENTITIES_PARIAH_NAMESHORT";
			texture="\A3\Characters_F_Tacops\Heads\Data\m_Sturrock_co.paa";
			material="\A3\Characters_F_Tacops\Heads\Data\m_Sturrock.rvmat";
		};
		class Ioannou: GreekHead_A3_01
		{
			author="$STR_A3_Bohemia_Interactive";
			displayName="$STR_A3_greekmen_lastnames18";
			texture="a3\Characters_F_Tank\Heads\data\m_Ioannou_co.paa";
			material="a3\Characters_F_Tank\Heads\data\m_Ioannou.rvmat";
			materialWounded1="a3\Characters_F_Tank\Heads\data\m_Ioannou_injury.rvmat";
			materialWounded2="a3\Characters_F_Tank\Heads\data\m_Ioannou_injury.rvmat";
			DLC="Tank";
		};
		class WhiteHead_24: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_WhiteHead_240";
			identityTypes[]={};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_3_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_3_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_capek_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_capek.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_capek_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_capek_injury.rvmat";
			DLC="Enoch";
		};
		class WhiteHead_25: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_WhiteHead_250";
			identityTypes[]={};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_dillon_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_dillon.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_dillon_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_dillon_injury.rvmat";
			DLC="Enoch";
		};
		class WhiteHead_26: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_WhiteHead_260";
			identityTypes[]={};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_4_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_4_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_homewood_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_homewood.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_homewood_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_homewood_injury.rvmat";
			DLC="Enoch";
		};
		class WhiteHead_27: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_WhiteHead_270";
			identityTypes[]={};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_kesson_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_kesson.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_kesson_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_kesson_injury.rvmat";
			DLC="Enoch";
		};
		class WhiteHead_28: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_WhiteHead_280";
			identityTypes[]={};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_kingsly_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_kingsly.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_kingsly_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_kingsly_injury.rvmat";
			DLC="Enoch";
		};
		class WhiteHead_29: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_WhiteHead_290";
			identityTypes[]={};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_kruglikov_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_kruglikov.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_kruglikov_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_kruglikov_injury.rvmat";
			DLC="Enoch";
		};
		class WhiteHead_30: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_WhiteHead_300";
			identityTypes[]=
			{
				"Head_Enoch"
			};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_smolko_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_smolko.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_smolko_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_smolko_injury.rvmat";
			DLC="Enoch";
		};
		class WhiteHead_31: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_WhiteHead_310";
			identityTypes[]={};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_stype_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_stype.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_stype_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_stype_injury.rvmat";
			DLC="Enoch";
		};
		class WhiteHead_32: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_WhiteHead_320";
			identityTypes[]={};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_rudwell_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_rudwell.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_rudwell_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_rudwell_injury.rvmat";
			DLC="Enoch";
		};
		class LivonianHead_1: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_LivonianHead_10";
			identityTypes[]=
			{
				"Head_Enoch"
			};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_livonianHead_1_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_livonianHead_1.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_livonianHead_1_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_livonianHead_1_injury.rvmat";
			DLC="Enoch";
		};
		class LivonianHead_2: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_LivonianHead_20";
			identityTypes[]=
			{
				"Head_Enoch"
			};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_livonianHead_2_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_livonianHead_2.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_livonianHead_2_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_livonianHead_2_injury.rvmat";
			DLC="Enoch";
		};
		class LivonianHead_3: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_LivonianHead_30";
			identityTypes[]=
			{
				"Head_Enoch"
			};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_livonianHead_3_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_livonianHead_3.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_livonianHead_3_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_livonianHead_3_injury.rvmat";
			DLC="Enoch";
		};
		class LivonianHead_4: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_LivonianHead_40";
			identityTypes[]=
			{
				"Head_Enoch"
			};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_livonianHead_4_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_livonianHead_4.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_livonianHead_4_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_livonianHead_4_injury.rvmat";
			DLC="Enoch";
		};
		class LivonianHead_5: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_LivonianHead_50";
			identityTypes[]=
			{
				"Head_Enoch"
			};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_1_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_1_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_livonianHead_5_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_livonianHead_5.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_livonianHead_5_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_livonianHead_5_injury.rvmat";
			DLC="Enoch";
		};
		class LivonianHead_6: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_LivonianHead_60";
			identityTypes[]=
			{
				"Head_Euro"
			};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_5_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_5_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_livonianHead_6_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_livonianHead_6.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_livonianHead_6_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_livonianHead_6_injury.rvmat";
			DLC="Enoch";
		};
		class LivonianHead_7: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_LivonianHead_70";
			identityTypes[]=
			{
				"Head_Enoch"
			};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_livonianHead_7_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_livonianHead_7.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_livonianHead_7_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_livonianHead_7_injury.rvmat";
			DLC="Enoch";
		};
		class LivonianHead_8: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_LivonianHead_80";
			identityTypes[]=
			{
				"Head_Enoch"
			};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_5_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_5_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_livonianHead_8_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_livonianHead_8.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_livonianHead_8_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_livonianHead_8_injury.rvmat";
			DLC="Enoch";
		};
		class LivonianHead_9: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_LivonianHead_90";
			identityTypes[]=
			{
				"Head_Enoch"
			};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_3_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_3_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_livonianHead_9_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_livonianHead_9.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_livonianHead_9_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_livonianHead_9_injury.rvmat";
			DLC="Enoch";
		};
		class LivonianHead_10: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_LivonianHead_100";
			identityTypes[]=
			{
				"Head_Enoch"
			};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_livonianHead_10_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_livonianHead_10.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_livonianHead_10_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_livonianHead_10_injury.rvmat";
			DLC="Enoch";
		};
		class RussianHead_1: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_RussianHead_10";
			identityTypes[]=
			{
				"Head_Russian"
			};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_5_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_5_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_russianHead_1_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_russianHead_1.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_russianHead_1_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_russianHead_1_injury.rvmat";
			DLC="Enoch";
		};
		class RussianHead_2: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_RussianHead_20";
			identityTypes[]=
			{
				"Head_Russian"
			};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_4_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_4_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_russianHead_2_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_russianHead_2.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_russianHead_2_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_russianHead_2_injury.rvmat";
			DLC="Enoch";
		};
		class RussianHead_3: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_RussianHead_30";
			identityTypes[]=
			{
				"Head_Russian"
			};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_4_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_4_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_russianHead_3_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_russianHead_3.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_russianHead_3_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_russianHead_3_injury.rvmat";
			DLC="Enoch";
		};
		class RussianHead_4: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_RussianHead_40";
			identityTypes[]=
			{
				"Head_Russian"
			};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_russianHead_4_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_russianHead_4.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_russianHead_4_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_russianHead_4_injury.rvmat";
			DLC="Enoch";
		};
		class RussianHead_5: WhiteHead_01
		{
			displayName="$STR_A3_C_CfgFaces_Man_A3_RussianHead_50";
			identityTypes[]=
			{
				"Head_Russian"
			};
			textureHL="\A3\Characters_F\Heads\Data\hl_White_bald_5_co.paa";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_bald_5_co.paa";
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Enoch\Heads\data\m_russianHead_5_co.paa";
			material="a3\Characters_F_Enoch\Heads\data\m_russianHead_5.rvmat";
			materialWounded1="a3\Characters_F_Enoch\Heads\data\m_russianHead_5_injury.rvmat";
			materialWounded2="a3\Characters_F_Enoch\Heads\data\m_russianHead_5_injury.rvmat";
			DLC="Enoch";
		};
		class AfricanHead_01_sick: AfricanHead_01
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="AfricanHead_01_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_african_01_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_african_01_sick.rvmat";
		};
		class AfricanHead_02_sick: AfricanHead_02
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="AfricanHead_02_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_african_02_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_african_02_sick.rvmat";
		};
		class AfricanHead_03_sick: AfricanHead_03
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="AfricanHead_03_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_african_03_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_african_03_sick.rvmat";
		};
		class AsianHead_A3_01_sick: AsianHead_A3_01
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="AsianHead_A3_01_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_asian_01_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_asian_01_sick.rvmat";
		};
		class AsianHead_A3_02_sick: AsianHead_A3_02
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="AsianHead_A3_02_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_asian_02_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_asian_02_sick.rvmat";
		};
		class AsianHead_A3_03_sick: AsianHead_A3_03
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="AsianHead_A3_03_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_asian_03_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_asian_03_sick.rvmat";
		};
		class AsianHead_A3_04_sick: AsianHead_A3_04
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="AsianHead_A3_04_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_asian_04_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_asian_04_sick.rvmat";
		};
		class AsianHead_A3_05_sick: AsianHead_A3_05
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="AsianHead_A3_05_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_asian_05_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_asian_05_sick.rvmat";
		};
		class AsianHead_A3_06_sick: AsianHead_A3_06
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="AsianHead_A3_06_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_asian_06_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_asian_06_sick.rvmat";
		};
		class AsianHead_A3_07_sick: AsianHead_A3_07
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="AsianHead_A3_07_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_asian_07_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_asian_07_sick.rvmat";
		};
		class GreekHead_A3_01_sick: GreekHead_A3_01
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="GreekHead_A3_01_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_greek_01_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_greek_01_sick.rvmat";
		};
		class GreekHead_A3_02_sick: GreekHead_A3_02
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="GreekHead_A3_02_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_greek_02_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_greek_02_sick.rvmat";
		};
		class GreekHead_A3_03_sick: GreekHead_A3_03
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="GreekHead_A3_03_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_greek_03_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_greek_03_sick.rvmat";
		};
		class GreekHead_A3_04_sick: GreekHead_A3_04
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="GreekHead_A3_04_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_greek_04_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_greek_04_sick.rvmat";
		};
		class PersianHead_A3_01_sick: PersianHead_A3_01
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="PersianHead_A3_01_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_persian_01_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_persian_01_sick.rvmat";
		};
		class PersianHead_A3_02_sick: PersianHead_A3_02
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="PersianHead_A3_02_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_persian_02_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_persian_02_sick.rvmat";
		};
		class PersianHead_A3_03_sick: PersianHead_A3_03
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="PersianHead_A3_03_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_persian_03_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_persian_03_sick.rvmat";
		};
		class TanoanHead_A3_01_sick: TanoanHead_A3_01
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="TanoanHead_A3_01_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_01_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_01_sick.rvmat";
		};
		class TanoanHead_A3_02_sick: TanoanHead_A3_02
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="TanoanHead_A3_02_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_02_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_02_sick.rvmat";
		};
		class TanoanHead_A3_03_sick: TanoanHead_A3_03
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="TanoanHead_A3_03_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_03_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_03_sick.rvmat";
		};
		class TanoanHead_A3_04_sick: TanoanHead_A3_04
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="TanoanHead_A3_04_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_04_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_04_sick.rvmat";
		};
		class TanoanHead_A3_05_sick: TanoanHead_A3_05
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="TanoanHead_A3_05_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_05_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_05_sick.rvmat";
		};
		class TanoanHead_A3_06_sick: TanoanHead_A3_06
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="TanoanHead_A3_06_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_06_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_06_sick.rvmat";
		};
		class TanoanHead_A3_07_sick: TanoanHead_A3_07
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="TanoanHead_A3_07_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_07_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_07_sick.rvmat";
		};
		class TanoanHead_A3_08_sick: TanoanHead_A3_08
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="TanoanHead_A3_08_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_08_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_08_sick.rvmat";
		};
		class TanoanBossHead_sick: TanoanBossHead
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="TanoanBossHead_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_boss_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_tanoan_boss_sick.rvmat";
		};
		class WhiteHead_16_sick: WhiteHead_16
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="WhiteHead_16_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_white_16_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_white_16_sick.rvmat";
		};
		class WhiteHead_17_sick: WhiteHead_17
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="WhiteHead_17_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_white_17_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_white_17_sick.rvmat";
		};
		class WhiteHead_18_sick: WhiteHead_18
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="WhiteHead_18_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_white_18_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_white_18_sick.rvmat";
		};
		class WhiteHead_19_sick: WhiteHead_19
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="WhiteHead_19_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_white_19_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_white_19_sick.rvmat";
		};
		class WhiteHead_20_sick: WhiteHead_20
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="WhiteHead_20_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_white_20_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_white_20_sick.rvmat";
		};
		class WhiteHead_21_sick: WhiteHead_21
		{
			disabled=1;
			author="$STR_A3_Bohemia_Interactive";
			displayname="WhiteHead_21_sick";
			identityTypes[]={};
			materialWounded1="\A3\Characters_F_Oldman\Heads\Data\m_white_21_sick.rvmat";
			materialWounded2="\A3\Characters_F_Oldman\Heads\Data\m_white_21_sick.rvmat";
		};
		class TanoanHead_A3_09: TanoanHead_A3_01
		{
			displayName="$STR_a3_missions_f_oldman_cfgmissions_missions_om_oldman1";
			identityTypes[]={};
			author="$STR_A3_Bohemia_Interactive";
			texture="a3\Characters_F_Oldman\Heads\data\m_old_man_co.paa";
			material="a3\Characters_F_Oldman\Heads\data\m_old_man.rvmat";
			materialWounded1="a3\Characters_F_Oldman\Heads\data\m_old_man_injury.rvmat";
			materialWounded2="a3\Characters_F_Oldman\Heads\data\m_old_man_injury.rvmat";
			textureHL="A3\Characters_F_Oldman\Heads\Data\hl_old_man_co.paa";
			materialHL="A3\Characters_F_Oldman\Heads\Data\hl_old_man.rvmat";
			textureHL2="A3\Characters_F_Oldman\Heads\Data\hl_old_man_co.paa";
			materialHL2="A3\Characters_F_Oldman\Heads\Data\hl_old_man.rvmat";
			DLC="Oldman";
		};
	};
	class Miller
	{
		class Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_A3_CfgFaces_Man_A3_Miller0";
			head="Miller";
			texture="\A3\Characters_F\Heads\Data\m_Miller_co.paa";
			identityTypes[]=
			{
				"Miller"
			};
			material="\A3\Characters_F\Heads\Data\m_Miller.rvmat";
			materialWounded1="A3\Characters_F\Heads\Data\m_Miller_injury.rvmat";
			materialWounded2="A3\Characters_F\Heads\Data\m_Miller_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			disabled=1;
		};
		class Miller: Default
		{
		};
	};
	class Kerry
	{
		class Default
		{
			head="KerryHead_A3";
			texture="\A3\Characters_F_EPA\Heads\Data\m_kerry_A_co.paa";
			identityTypes[]=
			{
				"Kerry"
			};
			material="A3\Characters_F_EPA\Heads\Data\m_kerry_A.rvmat";
			materialWounded1="A3\Characters_F_EPA\Heads\Data\m_kerry_A_injury.rvmat";
			materialWounded2="A3\Characters_F_EPA\Heads\Data\m_kerry_A_injury.rvmat";
			textureHL="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL="\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2="\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2="A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			disabled=1;
		};
		class Kerry: Default
		{
		};
		class Kerry_A_F: Default
		{
			identityTypes[]=
			{
				"Kerry_A"
			};
		};
		class kerry_B1_F: Default
		{
			texture="\A3\Characters_F_EPA\Heads\Data\m_kerry_B1_co.paa";
			identityTypes[]=
			{
				"kerry_B1"
			};
			material="A3\Characters_F_EPA\Heads\Data\m_kerry_B1.rvmat";
			materialWounded1="A3\Characters_F_EPA\Heads\Data\m_kerry_B1_injury.rvmat";
			materialWounded2="A3\Characters_F_EPA\Heads\Data\m_kerry_B1_injury.rvmat";
		};
		class kerry_B2_F: Default
		{
			texture="\A3\Characters_F_EPA\Heads\Data\m_kerry_B2_co.paa";
			identityTypes[]=
			{
				"kerry_B2"
			};
			material="A3\Characters_F_EPA\Heads\Data\m_kerry_B2.rvmat";
			materialWounded1="A3\Characters_F_EPA\Heads\Data\m_kerry_B2_injury.rvmat";
			materialWounded2="A3\Characters_F_EPA\Heads\Data\m_kerry_B2_injury.rvmat";
			textureHL="\A3\Characters_F_EPB\Heads\Data\hl_hairy_dirty_co.paa";
			materialHL="\A3\Characters_F_EPB\Heads\Data\hl_hairy_dirty.rvmat";
			textureHL2="\A3\Characters_F_EPB\Heads\Data\hl_hairy_dirty_co.paa";
			materialHL2="A3\Characters_F_EPB\Heads\Data\hl_hairy_dirty.rvmat";
		};
		class Kerry_C_F: Default
		{
			texture="\A3\Characters_F_EPA\Heads\Data\m_kerry_C_co.paa";
			identityTypes[]=
			{
				"Kerry_C"
			};
			material="A3\Characters_F_EPA\Heads\Data\m_kerry_C.rvmat";
			materialWounded1="A3\Characters_F_EPA\Heads\Data\m_kerry_C_injury.rvmat";
			materialWounded2="A3\Characters_F_EPA\Heads\Data\m_kerry_C_injury.rvmat";
		};
	};
	class IG_Leader
	{
		class Default
		{
			displayname="$STR_A3_I_G_resistanceLeader_F0";
			head="IG_Leader";
			texture="\A3\Characters_F_EPB\Heads\Data\m_IG_leader_co.paa";
			identityTypes[]=
			{
				"IG_Leader"
			};
			material="\A3\Characters_F_EPB\Heads\Data\m_IG_leader.rvmat";
			materialWounded1="A3\characters_F_EPB\Heads\Data\m_IG_leader_injury.rvmat";
			materialWounded2="A3\characters_F_EPB\Heads\Data\m_IG_leader_injury.rvmat";
			textureHL="\A3\Characters_F_EPB\Heads\Data\hl_Stavrou_dirty_co.paa";
			materialHL="\A3\Characters_F_EPB\Heads\Data\hl_stavrou_dirty.rvmat";
			textureHL2="\A3\Characters_F_EPB\Heads\Data\hl_Stavrou_dirty_co.paa";
			materialHL2="A3\Characters_F_EPB\Heads\Data\hl_stavrou_dirty.rvmat";
			disabled=1;
		};
		class IG_Leader: Default
		{
		};
	};
	class O_Colonel
	{
		class Default
		{
			displayname="$STR_A3_O_STORY_COLONEL_F0";
			head="PersianHead_A3";
			texture="\A3\Characters_F_EPB\Heads\Data\m_white_17_co.paa";
			identityTypes[]=
			{
				"O_Colonel"
			};
			material="\A3\Characters_F_EPB\Heads\Data\m_white_17.rvmat";
			materialWounded1="\A3\Characters_F_EPB\Heads\Data\m_white_17_injury.rvmat";
			materialWounded2="\A3\Characters_F_EPB\Heads\Data\m_white_17_injury.rvmat";
			disabled=1;
		};
		class O_Colonel: Default
		{
		};
	};
	class AnimalHead
	{
		class Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_FN_AnimalHead_Default";
			texture="\A3\Characters_F\Heads\Data\m_White_01_co.paa";
			head="";
			identityTypes[]=
			{
				"Animal"
			};
			material="";
		};
		class Animal: Default
		{
		};
	};
	class WomanHead_A3
	{
		class Default
		{
			author="$STR_A3_Bohemia_Interactive";
			displayname="$STR_CFG_FACES_Default";
			texture="\A3\Characters_F\Heads\Data\m_White_01_co.paa";
			head="WomanHead_A3";
			identityTypes[]=
			{
				"Woman"
			};
			material="";
			disabled=1;
		};
		class Woman_A3: Default
		{
		};
	};
};
