class CfgGlasses
{
	class None
	{
		name="$STR_A3_CfgGlasses_None0";
		model="";
		identityTypes[]=
		{
			"G_RUS_SF",
			50,
			"G_CIVIL_aidworker",
			200,
			"G_CIVIL_man",
			150,
			"G_CIVIL_paramedic",
			520,
			"G_CIVIL_constructionworker",
			220,
			"NoGlasses",
			1000,
			"G_NATO_default",
			300,
			"G_NATO_casual",
			550,
			"G_NATO_pilot",
			1000,
			"G_NATO_recon",
			595,
			"G_NATO_SF",
			300,
			"G_NATO_sniper",
			1000,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			1000,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			595,
			"G_HAF_default",
			595,
			"G_CIVIL_female",
			655,
			"G_CIVIL_male",
			670,
			"g_Rangemaster",
			0,
			"G_IRAN_officer",
			500
		};
		ACE_Color[]={0,0,0};
		ACE_TintAmount=0;
		ACE_Overlay="";
		ACE_OverlayDirt="A3\Ui_f\data\igui\rsctitles\HealthTextures\dust_upper_ca.paa";
		ACE_OverlayCracked="\z\ace\addons\goggles\textures\HUD\Cracked.paa";
		ACE_Resistance=0;
		ACE_Protection=0;
		ACE_DustPath="\z\ace\addons\goggles\textures\fx\dust\%1.paa";
		displayname="$STR_A3_cfgglasses_g_None";
		picture="\A3\Characters_F\data\ui\icon_g_aviators_CA.paa";
		mass=1;
		scope=2;
	};
	class G_Blindfold_01_base_F: None
	{
		ACE_Overlay="\z\ace\addons\goggles\textures\HUD\blindfold_ca.paa";
		ACE_OverlayCracked="";
		ACE_Resistance=2;
		ACE_Protection=1;
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		DLC="Enoch";
		model="\a3\Characters_F_Enoch\Facewear\G_Blindfold_01_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		mass=3;
		identityTypes[]={};
	};
	class G_Combat: None
	{
		ACE_Overlay="\z\ace\addons\goggles\textures\HUD\CombatGoggles.paa";
		ACE_OverlayCracked="\z\ace\addons\goggles\textures\HUD\CombatGogglesCracked.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Combat";
		displayname="$STR_A3_CfgGlasses_G_Combat0";
		model="\A3\characters_f_beta\heads\glasses\g_combat";
		picture="\A3\Characters_F\data\ui\icon_g_combat_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\g_combat_ca.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			300,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			300,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
		mass=4;
	};
	class G_Combat_Goggles_tna_F: None
	{
		ACE_Overlay="\z\ace\addons\goggles\textures\HUD\CombatGoggles.paa";
		ACE_OverlayCracked="\z\ace\addons\goggles\textures\HUD\CombatGogglesCracked.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Combat_Goggles_tna_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_G_Combat_Goggles_tna_F0";
		model="\A3\Characters_F_Beta\Heads\Glasses\g_combat.p3d";
		picture="\A3\Characters_F_Exp\BLUFOR\Data\UI\icon_G_Combat_Goggles_tna_F_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\BLUFOR\Data\G_Combat_Goggles_tna_F_ca.paa"
		};
		identityTypes[]={};
		mass=6;
		DLC="Expansion";
	};
	class G_Diving
	{
		ACE_Overlay="\z\ace\addons\goggles\textures\HUD\DivingGoggles.paa";
		ACE_OverlayCracked="\z\ace\addons\goggles\textures\HUD\DivingGogglesCracked.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Diving";
		displayname="$STR_A3_CfgGlasses_G_Diving0";
		descriptionUse="$str_a3_cfgglasses_g_diving1";
		model="\A3\characters_f\Heads\glasses\g_diving";
		picture="\A3\characters_F\data\ui\icon_G_Diving_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\g_diving_ca.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			1000,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			1000,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
		mode=1;
		mass=3;
		scope=2;
	};
	class G_Lowprofile: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=2;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Lowprofile";
		displayname="$STR_A3_CfgGlasses_G_Lowprofile0";
		model="\A3\characters_f_beta\heads\glasses\g_lowprofile";
		picture="\A3\Characters_F\data\ui\icon_g_lowprofile_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\lowprofile_black_ca.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			150,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
		mass=2;
	};
	class G_Shades_Black: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\joeyx_black_ca.paa"
		};
		identityTypes[]=
		{
			"G_CIVIL_aidworker",
			100,
			"G_CIVIL_constructionworker",
			120,
			"G_CIVIL_man",
			80,
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			20,
			"G_HAF_default",
			20,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20,
			"G_Competitor",
			10
		};
		mass=2;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Shades_Black";
		displayname="$STR_A3_CfgGlasses_G_Shades_Black0";
		model="\A3\characters_f\Heads\glasses\g_shades_black";
		picture="\A3\Characters_F\data\ui\icon_g_shades_black_CA.paa";
	};
	class G_Shades_Blue: None
	{
		ACE_Color[]={0,0,1};
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Shades_Blue";
		displayname="$STR_A3_CfgGlasses_G_Shades_Blue0";
		model="\A3\characters_f\heads\glasses\g_shades_blue";
		picture="\A3\Characters_F\data\ui\icon_g_shades_blue_CA.paa";
		identityTypes[]=
		{
			"G_CIVIL_aidworker",
			100,
			"G_CIVIL_constructionworker",
			60,
			"G_CIVIL_man",
			80,
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			20,
			"G_HAF_default",
			20,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20
		};
	};
	class G_Shades_Green: None
	{
		ACE_Color[]={0,1,0};
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Shades_Green";
		displayname="$STR_A3_CfgGlasses_G_Shades_Green0";
		model="\A3\characters_f_beta\heads\glasses\g_shades_green";
		picture="\A3\Characters_F\data\ui\icon_g_shades_green_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\joeyx_green_ca.paa"
		};
		identityTypes[]=
		{
			"G_CIVIL_aidworker",
			100,
			"G_CIVIL_constructionworker",
			60,
			"G_CIVIL_man",
			80,
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			20,
			"G_HAF_default",
			20,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20,
			"G_Competitor",
			10
		};
		mass=2;
	};
	class G_Shades_Red: None
	{
		ACE_Color[]={1,0,0};
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Shades_Red";
		displayname="$STR_A3_CfgGlasses_G_Shades_Red0";
		model="\A3\characters_f_beta\heads\glasses\g_shades_red";
		picture="\A3\Characters_F\data\ui\icon_g_shades_red_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\joeyx_red_ca.paa"
		};
		identityTypes[]=
		{
			"G_CIVIL_aidworker",
			100,
			"G_CIVIL_constructionworker",
			60,
			"G_CIVIL_man",
			80,
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			20,
			"G_HAF_default",
			20,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20,
			"G_Competitor",
			10
		};
		mass=2;
	};
	class G_Spectacles: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Spectacles";
		displayname="$STR_A3_CfgGlasses_G_Spectacles0";
		model="\A3\characters_f_beta\heads\glasses\g_spectacles";
		picture="\A3\Characters_F\data\ui\icon_g_spectacles_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\spectacles_brown_ca.paa"
		};
		identityTypes[]=
		{
			"G_CIVIL_aidworker",
			100,
			"G_CIVIL_constructionworker",
			120,
			"G_CIVIL_man",
			80,
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20
		};
		mass=2;
	};
	class G_Spectacles_Tinted: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Spectacles_Tinted";
		displayname="$STR_A3_CfgGlasses_G_Spectacles_Tinted0";
		model="\A3\characters_f_beta\heads\glasses\g_spectacles_tinted";
		picture="\A3\Characters_F\data\ui\icon_g_spectacles_tinted_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\spectacles_black_ca.paa"
		};
		identityTypes[]=
		{
			"G_CIVIL_aidworker",
			160,
			"G_CIVIL_constructionworker",
			120,
			"G_CIVIL_man",
			80,
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20
		};
		mass=2;
	};
	class G_Sport_Blackred: None
	{
		ACE_Color[]={1,0,0};
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Sport_Blackred";
		displayname="$STR_A3_CfgGlasses_G_Sport_Blackred0";
		model="\A3\characters_f\heads\glasses\g_sport_blackred";
		picture="\A3\Characters_F\data\ui\icon_g_sport_blackred_CA.paa";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
	};
	class G_Sport_BlackWhite: None
	{
		ACE_Color[]={0,0,1};
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Sport_BlackWhite";
		displayname="$STR_A3_CfgGlasses_G_Sport_BlackWhite0";
		model="\A3\characters_f_beta\heads\glasses\g_sport_blackWhite";
		picture="\A3\Characters_F\data\ui\icon_g_sport_blackwhite_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\sunglasses_sport_1_ca.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
		mass=2;
	};
	class G_Sport_Blackyellow: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Sport_Blackyellow";
		displayname="$STR_A3_CfgGlasses_G_Sport_Blackyellow0";
		model="\A3\characters_f_beta\heads\glasses\g_sport_blackyellow";
		picture="\A3\Characters_F\data\ui\icon_g_sport_blackyellow_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\sunglasses_sport_2_ca.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
		mass=2;
	};
	class G_Sport_Checkered: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Sport_Checkered";
		displayname="$STR_A3_CfgGlasses_G_Sport_Checkered0";
		model="\A3\characters_f_beta\heads\glasses\g_sport_checkered";
		picture="\A3\Characters_F\data\ui\icon_g_sport_checkered_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\sunglasses_sport_6_ca.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
		mass=2;
	};
	class G_Sport_Greenblack: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Sport_Greenblack";
		displayname="$STR_A3_CfgGlasses_G_Sport_Greenblack0";
		model="\A3\characters_f_beta\heads\glasses\g_sport_greenblack";
		picture="\A3\Characters_F\data\ui\icon_g_sport_greenblack_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\sunglasses_sport_3_ca.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
		mass=2;
	};
	class G_Sport_Red: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Color[]={0,0,0};
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Sport_Red";
		displayname="$STR_A3_CfgGlasses_G_Sport_Red0";
		model="\A3\characters_f_beta\heads\glasses\g_sport_red";
		picture="\A3\Characters_F\data\ui\icon_g_sport_red_CA.paa";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
		mass=2;
	};
	class G_Squares: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Squares";
		displayname="$STR_A3_CfgGlasses_G_Squares0";
		model="\A3\characters_f_beta\heads\glasses\g_squares";
		picture="\A3\Characters_F\data\ui\icon_g_squares_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\civil\data\nikos_wear_ca.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			15
		};
		mass=2;
	};
	class G_Squares_Tinted: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Squares_Tinted";
		displayname="$STR_A3_CfgGlasses_G_Squares_Tinted0";
		model="\A3\characters_f_beta\heads\glasses\g_squares_tinted";
		picture="\A3\Characters_F\data\ui\icon_g_squares_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\civil\data\nikos_wear_co.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			15
		};
		mass=2;
	};
	class G_Tactical_Black: None
	{
		ACE_TintAmount=8;
		ACE_Color[]={0,0,-1.5};
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Tactical_Black";
		displayname="$STR_A3_CfgGlasses_G_Tactical_Black0";
		model="\A3\characters_f_beta\heads\glasses\g_tactical_black";
		picture="\A3\Characters_F\data\ui\icon_g_tactical_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\tactical_3_ca.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			100,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			100,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0,
			"G_Competitor",
			10
		};
		mass=2;
	};
	class G_Tactical_Clear: None
	{
		ACE_TintAmount=8;
		ACE_Color[]={0,0,-1};
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Tactical_Clear";
		displayname="$STR_A3_CfgGlasses_G_Tactical_Clear0";
		model="\A3\characters_f\heads\glasses\g_tactical_clear";
		picture="\A3\Characters_F\data\ui\icon_g_tactical_CA.paa";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			250,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			250,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0,
			"G_Rangemaster",
			1
		};
	};
	class G_Aviator: None
	{
		ACE_Color[]={0,0,-1};
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Aviator";
		displayname="$STR_A3_CfgGlasses_G_Aviator0";
		model="\A3\characters_f_gamma\Heads\Glasses\g_aviators";
		picture="\A3\Characters_F\data\ui\icon_g_aviators_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\glass_ca.paa"
		};
		identityTypes[]=
		{
			"G_CIVIL_aidworker",
			100,
			"G_CIVIL_constructionworker",
			60,
			"G_CIVIL_man",
			80,
			"NoGlasses",
			0,
			"G_NATO_default",
			50,
			"G_NATO_casual",
			450,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			15,
			"G_NATO_SF",
			50,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			25,
			"G_HAF_default",
			25,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			30,
			"G_IRAN_officer",
			500
		};
		mass=2;
	};
	class G_Lady_Blue: None
	{
		ACE_Color[]={0,0,1};
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Lady_Blue";
		displayname="$STR_A3_CfgGlasses_G_Lady_Blue0";
		model="\A3\characters_f_gamma\Heads\Glasses\g_lady_blue";
		picture="\A3\Characters_F\data\ui\icon_g_lady_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f\heads\glasses\data\glass_ca.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			40,
			"G_CIVIL_male",
			0
		};
		mass=2;
	};
	class G_Lady_Red: None
	{
		ACE_Color[]={1,0,0};
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Lady_Red";
		scope=1;
		displayname="$STR_A3_CfgGlasses_G_Lady_Red0";
		model="\A3\characters_f_gamma\Heads\Glasses\g_lady_red";
		picture="\A3\Characters_F\data\ui\icon_g_lady_CA.paa";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			40,
			"G_CIVIL_male",
			0
		};
		mass=2;
	};
	class G_Lady_Dark: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Lady_Dark";
		scope=1;
		displayname="$STR_A3_CfgGlasses_G_Lady_Dark0";
		model="\A3\characters_f_gamma\Heads\Glasses\g_lady_dark";
		picture="\A3\Characters_F\data\ui\icon_g_lady_CA.paa";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			40,
			"G_CIVIL_male",
			0
		};
		mass=2;
	};
	class G_Lady_Mirror: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Lady_Mirror";
		scope=1;
		displayname="$STR_A3_CfgGlasses_G_Lady_Mirror0";
		model="\A3\characters_f_gamma\Heads\Glasses\g_lady_mirror";
		picture="\A3\Characters_F\data\ui\icon_g_lady_CA.paa";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			40,
			"G_CIVIL_male",
			0
		};
		mass=2;
	};
	class G_Balaclava_blk: None
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Balaclava_blk";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_clean0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_balaclava_clean.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Balaclava_clean_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_bootcamp\guerrilla\data\headgear_balaclava_blk_co.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_RUS_SF",
			25
		};
		mass=6;
	};
	class G_Balaclava_combat: G_Balaclava_blk
	{
		ACE_Overlay="\z\ace\addons\goggles\textures\HUD\CombatGoggles.paa";
		ACE_OverlayCracked="\z\ace\addons\goggles\textures\HUD\CombatGogglesCracked.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Balaclava_combat";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_combat0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_balaclava_combat.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Balaclava_combat_ca.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_bootcamp\guerrilla\data\headgear_balaclava_blk_co.paa",
			"\a3\characters_f\heads\glasses\data\g_combat_ca.paa"
		};
		mass=10;
		identityTypes[]={};
	};
	class G_Balaclava_lowprofile: G_Balaclava_blk
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=2;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Balaclava_lowprofile";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_lowprofile0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_balaclava_lowprofile.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Balaclava_lowprofile_ca.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_bootcamp\guerrilla\data\headgear_balaclava_blk_co.paa",
			"\a3\characters_f\heads\glasses\data\lowprofile_black_ca.paa"
		};
		mass=8;
		identityTypes[]={};
	};
	class G_Balaclava_TI_blk_F: None
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Balaclava_TI_blk_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_G_Balaclava_TI_blk_F0";
		model="\A3\Characters_F_Exp\BLUFOR\G_Balaclava_TI_F.p3d";
		picture="\A3\Characters_F_Exp\BLUFOR\Data\UI\icon_G_Balaclava_TI_blk_F_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\BLUFOR\Data\G_Balaclava_TI_blk_F_co.paa"
		};
		identityTypes[]={};
		mass=6;
		DLC="Expansion";
	};
	class G_Balaclava_TI_G_blk_F: G_Balaclava_TI_blk_F
	{
		ACE_Overlay="\z\ace\addons\goggles\textures\HUD\CombatGoggles.paa";
		ACE_OverlayCracked="\z\ace\addons\goggles\textures\HUD\CombatGogglesCracked.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Balaclava_TI_G_blk_F";
		displayName="$STR_A3_G_Balaclava_TI_G_blk_F0";
		model="\A3\Characters_F_Exp\BLUFOR\G_Balaclava_TI_G_F.p3d";
		picture="\A3\Characters_F_Exp\BLUFOR\Data\UI\icon_G_Balaclava_TI_G_blk_F_ca.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\BLUFOR\Data\G_Balaclava_TI_blk_F_co.paa",
			"\A3\Characters_F\Heads\Glasses\data\g_combat_ca.paa"
		};
		identityTypes[]={};
		mass=10;
		DLC="Expansion";
	};
	class G_Balaclava_TI_tna_F: G_Balaclava_TI_blk_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Balaclava_TI_tna_F";
		displayName="$STR_A3_G_Balaclava_TI_tna_F0";
		picture="\A3\Characters_F_Exp\BLUFOR\Data\UI\icon_G_Balaclava_TI_tna_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\BLUFOR\Data\G_Balaclava_TI_tna_F_co.paa"
		};
		identityTypes[]={};
		mass=6;
		DLC="Expansion";
	};
	class G_Balaclava_TI_G_tna_F: G_Balaclava_TI_tna_F
	{
		ACE_Overlay="\z\ace\addons\goggles\textures\HUD\CombatGoggles.paa";
		ACE_OverlayCracked="\z\ace\addons\goggles\textures\HUD\CombatGogglesCracked.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Balaclava_TI_G_tna_F";
		displayName="$STR_A3_G_Balaclava_TI_G_tna_F0";
		model="\A3\Characters_F_Exp\BLUFOR\G_Balaclava_TI_G_F.p3d";
		picture="\A3\Characters_F_Exp\BLUFOR\Data\UI\icon_G_Balaclava_TI_G_tna_F_ca.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\BLUFOR\Data\G_Balaclava_TI_tna_F_co.paa",
			"\A3\Characters_F\Heads\Glasses\data\g_combat_ca.paa"
		};
		identityTypes[]={};
		mass=10;
		DLC="Expansion";
	};
	class G_Bandanna_blk: G_Balaclava_blk
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Bandanna_blk";
		displayName="$STR_A3_CFGGLASSES_G_Bandana_clean0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_bandana_clean.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Bandana_clean_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_bootcamp\guerrilla\data\headgear_bandmask_blk_co.paa"
		};
		mass=4;
		identityTypes[]={};
	};
	class G_Bandanna_shades: G_Bandanna_blk
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Bandanna_shades";
		displayName="$STR_A3_CFGGLASSES_G_Bandana_shades0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_bandana_shades.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Bandana_shades_ca.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_bootcamp\guerrilla\data\headgear_bandmask_blk_co.paa",
			"\a3\characters_f\heads\glasses\data\joeyx_black_ca.paa"
		};
		mass=6;
	};
	class G_Bandanna_sport: G_Bandanna_shades
	{
		ACE_Color[]={1,0,0};
		ACE_TintAmount=8;
		ACE_Resistance=1;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Bandanna_sport";
		displayName="$STR_A3_CFGGLASSES_G_Bandana_sport0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_bandana_sport.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Bandana_sport_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_bootcamp\guerrilla\data\headgear_bandmask_blk_co.paa",
			"\a3\characters_f\heads\glasses\data\sunglasses_sport_4_ca.paa"
		};
	};
	class G_Bandanna_aviator: G_Bandanna_shades
	{
		ACE_Color[]={0,0,-1};
		ACE_TintAmount=8;
		ACE_Resistance=1;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Bandanna_aviator";
		displayName="$STR_A3_CFGGLASSES_G_Bandana_aviator0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_bandana_aviator.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Bandana_aviator_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_bootcamp\guerrilla\data\headgear_bandmask_blk_co.paa",
			"\a3\characters_f\heads\glasses\data\glass_ca.paa"
		};
	};
	class G_EyeProtectors_base_F: None
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_EyeProtectors_base_F";
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		DLC="Orange";
		model="\A3\Characters_F_Orange\Facewear\G_EyeProtectors_F.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		mass=2;
		identityTypes[]={};
	};
	class G_EyeProtectors_F: G_EyeProtectors_base_F
	{
		ACE_Resistance=1;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_EyeProtectors_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_CfgGlasses_G_EyeProtectors_F0";
		picture="\A3\Characters_F_Orange\Facewear\Data\UI\icon_G_EyeProtectors_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Orange\Facewear\Data\G_EyeProtectors_ca.paa"
		};
		identityTypes[]=
		{
			"G_CIVIL_constructionworker",
			420
		};
	};
	class G_EyeProtectors_Earpiece_F: G_EyeProtectors_base_F
	{
		ACE_Resistance=1;
		ACE_Protection=1;
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_EyeProtectors_Earpiece_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		model="\A3\Characters_F_Orange\Facewear\G_EyeProtectors_Earpiece_F.p3d";
		displayName="$STR_A3_CfgGlasses_G_EyeProtectors_Earpiece_F0";
		picture="\A3\Characters_F_Orange\Facewear\Data\UI\icon_G_EyeProtectors_Earpiece_ca.paa";
		hiddenSelections[]=
		{
			"Camo",
			"Camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Orange\Facewear\Data\G_EyeProtectors_ca.paa",
			"\A3\Characters_F_Orange\Headgear\Data\H_WirelessEarpiece_co.paa"
		};
		mass=4;
		identityTypes[]=
		{
			"G_CIVIL_constructionworker",
			220
		};
	};
	class G_AirPurifyingRespirator_01_base_F: None
	{
		ACE_Overlay="a3\ui_f_enoch\data\objects\data\optics_apr_ca.paa";
		ACE_OverlayCracked="";
		ACE_Resistance=2;
		ACE_Protection=1;
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		DLC="Enoch";
		model="\a3\Characters_F_Enoch\Facewear\G_AirPurifyingRespirator_01_F.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		mass=8;
		identityTypes[]={};
	};
	class G_AirPurifyingRespirator_02_base_F: G_AirPurifyingRespirator_01_base_F
	{
		ACE_Overlay="a3\ui_f_enoch\data\objects\data\optics_APR_02_CA.paa";
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		DLC="Enoch";
		model="\a3\Characters_F_Enoch\Facewear\G_AirPurifyingRespirator_02_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		mass=8;
		identityTypes[]={};
	};
	class G_RegulatorMask_base_F: None
	{
		ACE_Overlay="a3\ui_f_enoch\data\objects\data\optics_regulator_ca.paa";
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		DLC="Enoch";
		model="\a3\Characters_F_Enoch\Facewear\G_RegulatorMask_F.p3d";
		hiddenSelections[]={};
		mass=8;
		identityTypes[]={};
	};
	class G_B_Diving: G_Diving
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_B_Diving";
		displayname="$STR_A3_CfgGlasses_G_B_Diving0";
		model="\A3\Characters_F_EPB\Heads\Glasses\g_b_diving.p3d";
		picture="\A3\Characters_F_EPB\Heads\Glasses\data\UI\icon_g_diving_nato_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_epb\heads\glasses\data\g_diving_nato_ca.paa"
		};
		mass=4;
	};
	class G_O_Diving: G_Diving
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_O_Diving";
		displayname="$STR_A3_CfgGlasses_G_O_Diving0";
		model="\A3\Characters_F_EPB\Heads\Glasses\g_o_diving.p3d";
		picture="\A3\Characters_F_EPB\Heads\Glasses\data\UI\icon_g_diving_iran_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_epb\heads\glasses\data\g_diving_iran_ca.paa"
		};
		mass=4;
	};
	class G_I_Diving: G_Diving
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_I_Diving";
		displayname="$STR_A3_CfgGlasses_G_I_Diving0";
		model="\A3\Characters_F_EPB\Heads\Glasses\g_i_diving.p3d";
		picture="\A3\Characters_F_EPB\Heads\Glasses\data\UI\icon_g_diving_rus_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_epb\heads\glasses\data\g_diving_rus_ca.paa"
		};
		mass=4;
	};
	class G_Goggles_VR: None
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Goggles_VR";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_CFGGLASSES_G_Goggles_VR0";
		model="\A3\Characters_F_Bootcamp\Common\G_vr.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Goggles_VR_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_bootcamp\common\data\g_vr_co.paa"
		};
		identityTypes[]={};
		mass=6;
	};
	class G_Balaclava_oli: G_Balaclava_blk
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Balaclava_oli";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_oli0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_balaclava_clean.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Balaclava_olive_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Bootcamp\Guerrilla\Data\headgear_balaclava_grn_co.paa"
		};
		identityTypes[]={};
	};
	class G_Bandanna_oli: G_Bandanna_blk
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Bandanna_oli";
		displayName="$STR_A3_CFGGLASSES_G_Bandanna_oli0";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_BandMask_olive_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Bootcamp\Guerrilla\Data\headgear_bandMask_grn_co.paa"
		};
	};
	class G_Bandanna_khk: G_Bandanna_blk
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Bandanna_khk";
		displayName="$STR_A3_CFGGLASSES_G_Bandanna_khk0";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_BandMask_khaki_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Bootcamp\Guerrilla\Data\headgear_bandMask_khk_co.paa"
		};
	};
	class G_Bandanna_tan: G_Bandanna_blk
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Bandanna_tan";
		displayName="$STR_A3_CFGGLASSES_G_Bandanna_tan0";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_BandMask_tan_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Bootcamp\Guerrilla\Data\headgear_bandMask_tan_co.paa"
		};
	};
	class G_Bandanna_beast: G_Bandanna_blk
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Bandanna_beast";
		displayName="$STR_A3_CFGGLASSES_G_Bandanna_beast0";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_BandMask_beast_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Bootcamp\Guerrilla\Data\headgear_bandMask_beast_co.paa"
		};
	};
	class G_Respirator_base_F: None
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Respirator_base_F";
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		DLC="Orange";
		model="\A3\Characters_F_Orange\Facewear\G_Respirator_F.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		mass=2;
		identityTypes[]={};
	};
	class G_Respirator_white_F: G_Respirator_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Respirator_white_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_CfgGlasses_G_Respirator_white_F0";
		picture="\A3\Characters_F_Orange\Facewear\Data\UI\icon_G_Respirator_white_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Orange\Facewear\Data\G_Respirator_white_co.paa"
		};
		identityTypes[]=
		{
			"G_CIVIL_paramedic",
			820,
			"G_CIVIL_constructionworker",
			120
		};
	};
	class G_Respirator_yellow_F: G_Respirator_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Respirator_yellow_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_CfgGlasses_G_Respirator_yellow_F0";
		picture="\A3\Characters_F_Orange\Facewear\Data\UI\icon_G_Respirator_yellow_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Orange\Facewear\Data\G_Respirator_yellow_co.paa"
		};
		identityTypes[]=
		{
			"G_CIVIL_paramedic",
			420,
			"G_CIVIL_constructionworker",
			420
		};
	};
	class G_Respirator_blue_F: G_Respirator_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Respirator_blue_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_CfgGlasses_G_Respirator_blue_F0";
		picture="\A3\Characters_F_Orange\Facewear\Data\UI\icon_G_Respirator_blue_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Orange\Facewear\Data\G_Respirator_blue_co.paa"
		};
		identityTypes[]=
		{
			"G_CIVIL_paramedic",
			420,
			"G_CIVIL_constructionworker",
			420
		};
	};
	class G_WirelessEarpiece_base_F: None
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_WirelessEarpiece_base_F";
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		DLC="Orange";
		model="\A3\Characters_F_Orange\Headgear\H_WirelessEarpiece_F.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Orange\Headgear\Data\H_WirelessEarpiece_co.paa"
		};
		mass=2;
		identityTypes[]={};
	};
	class G_WirelessEarpiece_F: G_WirelessEarpiece_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_WirelessEarpiece_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"G_CIVIL_aidworker",
			310
		};
		displayName="$STR_A3_CfgGlasses_G_WirelessEarpiece_F0";
		picture="\A3\Characters_F_Orange\Headgear\Data\UI\icon_H_WirelessEarpiece_CA.paa";
	};
	class G_AirPurifyingRespirator_01_F: G_AirPurifyingRespirator_01_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_AirPurifyingRespirator_01_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_C_CfgGlasses_G_AirPurifyingRespirator_01_F0";
		picture="\A3\Characters_F_Enoch\Facewear\Data\UI\icon_G_AirPurifyingRespirator_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"a3\characters_f_enoch\facewear\data\airpurifyingrespirator_co.paa"
		};
	};
	class G_AirPurifyingRespirator_01_nofilter_F: G_AirPurifyingRespirator_01_F
	{
		scope=1;
		scopeArsenal=0;
		hiddenSelections[]=
		{
			"Camo",
			"filter"
		};
	};
	class G_AirPurifyingRespirator_02_black_F: G_AirPurifyingRespirator_02_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_AirPurifyingRespirator_02_black_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_C_CfgGlasses_G_AirPurifyingRespirator_02_black_F0";
		picture="\A3\Characters_F_Enoch\Facewear\Data\UI\icon_G_AirPurifyingRespirator_02_black_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Enoch\Facewear\data\AirPurifyingRespirator_02_black_co"
		};
	};
	class G_AirPurifyingRespirator_02_black_nofilter_F: G_AirPurifyingRespirator_02_black_F
	{
		scope=1;
		scopeArsenal=0;
		hiddenSelections[]=
		{
			"Camo",
			"filter"
		};
	};
	class G_AirPurifyingRespirator_02_olive_F: G_AirPurifyingRespirator_02_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_AirPurifyingRespirator_02_olive_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_C_CfgGlasses_G_AirPurifyingRespirator_02_olive_F0";
		picture="\A3\Characters_F_Enoch\Facewear\Data\UI\icon_G_AirPurifyingRespirator_02_olive_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Enoch\Facewear\data\AirPurifyingRespirator_02_olive_co"
		};
	};
	class G_AirPurifyingRespirator_02_olive_nofilter_F: G_AirPurifyingRespirator_02_olive_F
	{
		scope=1;
		scopeArsenal=0;
		hiddenSelections[]=
		{
			"Camo",
			"filter"
		};
	};
	class G_AirPurifyingRespirator_02_sand_F: G_AirPurifyingRespirator_02_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_AirPurifyingRespirator_02_sand_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_C_CfgGlasses_G_AirPurifyingRespirator_02_sand_F0";
		picture="\A3\Characters_F_Enoch\Facewear\Data\UI\icon_G_AirPurifyingRespirator_02_sand_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Enoch\Facewear\data\AirPurifyingRespirator_02_sand_co"
		};
	};
	class G_AirPurifyingRespirator_02_sand_nofilter_F: G_AirPurifyingRespirator_02_sand_F
	{
		scope=1;
		scopeArsenal=0;
		hiddenSelections[]=
		{
			"Camo",
			"filter"
		};
	};
	class G_RegulatorMask_F: G_RegulatorMask_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_RegulatorMask_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_C_CfgGlasses_G_RegulatorMask_F0";
		picture="\A3\Characters_F_Enoch\Facewear\Data\UI\icon_G_RegulatorMask_F_ca.paa";
		hiddenSelectionsTextures[]={};
	};
	class G_Blindfold_01_white_F: G_Blindfold_01_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Blindfold_01_white_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_C_CfgGlasses_G_Blindfold_01_white_F0";
		picture="\A3\Characters_F_Enoch\Facewear\Data\UI\icon_G_Blindfold_01_white_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Enoch\Facewear\data\G_Blindfold_01_White_CO"
		};
	};
	class G_Blindfold_01_black_F: G_Blindfold_01_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Blindfold_01_black_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_C_CfgGlasses_G_Blindfold_01_black_F0";
		picture="\A3\Characters_F_Enoch\Facewear\Data\UI\icon_G_Blindfold_01_black_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Enoch\Facewear\data\G_Blindfold_01_Black_CO"
		};
	};
};
